	-- Pruebas
	-- SELECT * FROM WeeGigDB.JOB_APPLICATION;
    SELECT * FROM WeeGigDB.JOB_OFFERS;
    SELECT * FROM WeeGigDB.REVIEWS;
    -- SELECT * FROM WeeGigDB.REVIEW_DATE;
    -- SELECT * FROM WeeGigDB.USERS;
    -- SELECT * FROM WeeGigDB.LOGIN;
    -- DROP TABLE IF EXISTS `WeeGigDB`.`REVIEW_DATE`;
    -- DELETE FROM `WeeGigDB`.`job_application`;
	-- DELETE FROM `WeeGigDB`.`LOGIN`;
	-- DELETE FROM `WeeGigDB`.`USERS`;
	-- DELETE * FROM WeeGigDB.JOB_APPLICATION;
	-- SELECT * FROM WeeGigDB.USERS WHERE id_USER = 1;
    DROP DATABASE WeeGigDB;
	-- ALTER TABLE `WeeGigDB`.`JOB_OFFERS` MODIFY `description` VARCHAR(255);
      
      
      DROP TABLE REVIEWS;