-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 09:33:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLOYERS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYERS` (
  `idEMPLOYER` INT NOT NULL DEFAULT 1,
  `companyName` VARCHAR(45) NOT NULL,
  `companyNIF` VARCHAR(9) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `companyPhoneNumber` VARCHAR(12) NOT NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`idEMPLOYER`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LOGIN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LOGIN` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USERS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USERS` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `typeOfDocument` INT NOT NULL,
  `document` VARCHAR(9) NOT NULL,
  `phoneNumber` VARCHAR(12) NOT NULL,
  `birthdate` DATE NOT NULL,
  `typeOfUser` INT NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`idUSER`),
  UNIQUE INDEX `idUSER_UNIQUE` (`idUSER` ASC) VISIBLE,
  INDEX `isEmployer_idx` (`typeOfUser` ASC) VISIBLE,
  INDEX `emailLogin` (`email` ASC) VISIBLE,
  CONSTRAINT `isEmployer`
    FOREIGN KEY (`typeOfUser`)
    REFERENCES `mydb`.`EMPLOYERS` (`idEMPLOYER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emailLogin`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`LOGIN` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JOB_OFFERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JOB_OFFERS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JOB_OFFERS` (
  `idJOB_OFFERS` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `typeOfPayment` VARCHAR(45) NULL,
  `payment` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `schedule` DATETIME NULL,
  `category` VARCHAR(45) NULL,
  `idEmployer` INT NULL,
  `idEmployees` INT NULL,
  PRIMARY KEY (`idJOB_OFFERS`),
  INDEX `idEmployees` (`idEmployees` ASC) VISIBLE,
  INDEX `idEmployer` (`idEmployer` ASC) VISIBLE,
  CONSTRAINT `offerCreator`
    FOREIGN KEY (`idEmployer`)
    REFERENCES `mydb`.`USERS` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JOB_APPLICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JOB_APPLICATION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JOB_APPLICATION` (
  `idUSER` INT NOT NULL,
  `idEmployees` INT NOT NULL,
  `applicationDate` VARCHAR(45) NULL,
  `applicationStatus` VARCHAR(45) NULL,
  PRIMARY KEY (`idUSER`, `idEmployees`),
  INDEX `employer_idx` (`idEmployees` ASC) VISIBLE,
  CONSTRAINT `employer`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`JOB_OFFERS` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `username`
    FOREIGN KEY (`idUSER`)
    REFERENCES `mydb`.`USERS` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REVIEWS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`REVIEWS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`REVIEWS` (
  `idREVIEWS` INT NOT NULL AUTO_INCREMENT,
  `reviewTitle` VARCHAR(45) NULL,
  `reviewContent` VARCHAR(45) NULL,
  `rating` INT NULL,
  PRIMARY KEY (`idREVIEWS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REVIEW_DATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`REVIEW_DATE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`REVIEW_DATE` (
  `idReview` INT NOT NULL,
  `idReviewer` INT NOT NULL,
  `idJob` INT NOT NULL,
  `reviewDate` VARCHAR(45) NULL,
  `idReviewed` INT NOT NULL,
  PRIMARY KEY (`idReview`, `idReviewer`, `idJob`),
  INDEX `idReviewer_idx` (`idReviewer` ASC) VISIBLE,
  INDEX `idJob_idx` (`idJob` ASC) VISIBLE,
  CONSTRAINT `idReview`
    FOREIGN KEY (`idReview`)
    REFERENCES `mydb`.`REVIEWS` (`idREVIEWS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idReviewer`
    FOREIGN KEY (`idReviewer`)
    REFERENCES `mydb`.`USERS` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idJob`
    FOREIGN KEY (`idJob`)
    REFERENCES `mydb`.`JOB_OFFERS` (`idJOB_OFFERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
